export const MOCK_INCIDENTS = [
  {
    id: "#INC-001",
    severity: "Critical",
    status: "Active",
    title: "Traffic Accident - Route 5",
    reportedDate: "06.05.2023",
    reportedLocation: "Downtown District, NY 12345",
    reportedAddress: "123 Main St",
    expectedResolutionDate: "12.05.2023",
    resolutionLocation: "Downtown District, NY 12345",
    resolutionAddress: "123 Main St",
    reportedBy: "Officer John Smith",
    responders: "Unit Alpha",
    respondersPhone: "+1 555 012 0295",
    respondersEmail: "unit.alpha@police.ny",
    dispatchTime: "12.08.2022, 8:30",
    description:
      "Multi-vehicle collision. Clear traffic and establish safety perimeter.",
    incidentType: "Traffic Accident",
    estimatedAffectedArea: "2 km radius",
  },
  {
    id: "#INC-002",
    severity: "High",
    status: "In Progress",
    title: "Structural Fire - Commercial Building",
    reportedDate: "08.05.2023",
    reportedLocation: "Industrial Zone, NY 12345",
    reportedAddress: "789 Oak Dr",
    expectedResolutionDate: "10.05.2023",
    resolutionLocation: "Industrial Zone, NY 12345",
    resolutionAddress: "789 Oak Dr",
    reportedBy: "Fire Dispatcher",
    responders: "Fire Unit 5",
    respondersPhone: "+1 555 034 5678",
    respondersEmail: "fireunit5@fdny.ny",
    dispatchTime: "08.05.2023, 14:45",
    description:
      "Commercial building fire. Evacuate surrounding buildings immediately.",
    incidentType: "Fire",
    estimatedAffectedArea: "500m radius",
  },
  {
    id: "#INC-003",
    severity: "Medium",
    status: "Pending",
    title: "Road Closure - Maintenance Work",
    reportedDate: "10.05.2023",
    reportedLocation: "Lakeside Avenue, IL 67890",
    reportedAddress: "456 Tanager Drive",
    expectedResolutionDate: "12.05.2023",
    resolutionLocation: "Lakeside Avenue, IL 67890",
    resolutionAddress: "456 Tanager Drive",
    reportedBy: "Street Department",
    responders: "Traffic Control Unit",
    respondersPhone: "+1 555 056 7890",
    respondersEmail: "traffic.control@city.il",
    dispatchTime: "10.05.2023, 06:00",
    description:
      "Scheduled maintenance. Set up detour routes and warning signs.",
    incidentType: "Road Closure",
    estimatedAffectedArea: "1.2 km",
  },
];
